name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load node-version from .tool-version
        id: node-version
        run: echo ::set-output name=node-version::$(cat .tool-versions)

      # https://github.com/actions/setup-node#caching-global-packages-data
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - run: npm ci

      - run: npm run lint



